Emergency mode development and other changes
Technopy311/UBike pull request #3
Opened 2024-06-22 19:06 UTC by discojapi

# Changelog
- New emergency mode (WIP)
- Deleted junk .gcode file
- Programmed some of the colors of the LED indicator

2024-06-22 21:33 UTC, Technopy311 requested changes

2024-06-22 21:33 UTC, Technopy311 commented on esp32/main/main.ino
> +  if (WiFi.status() == WL_CONNECTED)
Missing bracket, syntax error

2024-06-22 21:33 UTC, Technopy311 commented on esp32/main/main.ino
> +const int pss = 0; // Primary Secure System pinout
change variable name. It is not descriptive.

2024-06-22 21:33 UTC, Technopy311 commented on esp32/main/main.ino
> +  if (WiFi.status() == WL_CONNECTED) {
Thanks for the bracket back.

2024-06-22 21:33 UTC, Technopy311 commented on esp32/main/main.ino
> +      status = -1
missing semicolon, syntax error.

2024-06-22 21:33 UTC, Technopy311 commented on esp32/main/main.ino
> +      rgb_set(0, 1, 0)
Missing semicolon, syntax error.

2024-06-22 21:33 UTC, Technopy311 commented on esp32/main/main.ino
> +      rgb_set(0, 0, 1)
Missing semicolon, syntax error.

2024-06-22 21:33 UTC, Technopy311 commented on esp32/main/main.ino
> +  if (status == -1){
Add short comments per if/else if.

2024-06-23 01:14 UTC, discojapi reviewed
TMPFM : Too Much Python For Me.
Correcting

2024-06-23 03:13 UTC, Technopy311 approved these changes

2024-06-23 03:15 UTC, merged